### ISSUE TITLE
error function :crypto.rand_bytes/1 is undefined or private

### ISSUE THREAD

**Issue by romaluca** [scrogson/romeo#39]
Hi i'm trying to use romeo for fcm.

With:
`{:ok, pid} = Conn.start_link(params)`
i receive this log:
```

[info] Established connection to fcm-xmpp.googleapis.com
[info] Negotiating secure connection
[info] Connection successfully secured
[debug] [xxxxx@gcm.googleapis.com]
[OUTGOING] "<stream:stream to='gcm.googleapis.com' version='1.0' xml:lang='en' xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams'>"
[debug] [xxxxxx@gcm.googleapis.com]
[INCOMING] "<stream:stream from=\"gcm.googleapis.com\" id=\"7Bxxxx147A02E00A\" version=\"1.0\" xmlns:stream=\"http://etherx.jabber.org/streams\" xmlns=\"jabber:client\">"
[debug] [xxxx@gcm.googleapis.com]
[INCOMING] "<stream:features><mechanisms xmlns=\"urn:ietf:params:xml:ns:xmpp-sasl\"><mechanism>X-OAUTH2</mechanism><mechanism>X-GOOGLE-TOKEN</mechanism><mechanism>PLAIN</mechanism></mechanisms></stream:features>"
[info] Authenticating with PLAIN
[debug] [xxxxx@gcm.googleapis.com]
[OUTGOING] "<auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='PLAIN'>xxxxxx</auth>"
[debug] [xxxxx@gcm.googleapis.com]
[INCOMING] "<success xmlns=\"urn:ietf:params:xml:ns:xmpp-sasl\"/>"
[info] Authenticated successfully
[debug] [xxxxx@gcm.googleapis.com]
[OUTGOING] "<stream:stream to='gcm.googleapis.com' version='1.0' xml:lang='en' xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams'>"
[debug] [xxxxx@gcm.googleapis.com]
[INCOMING] "<stream:stream from=\"gcm.googleapis.com\" id=\"xxxxxBAA404\" version=\"1.0\" xmlns:stream=\"http://etherx.jabber.org/streams\" xmlns=\"jabber:client\">"
[debug] [xxxxx@gcm.googleapis.com]
[INCOMING] "<stream:features><bind xmlns=\"urn:ietf:params:xml:ns:xmpp-bind\"/><session xmlns=\"urn:ietf:params:xml:ns:xmpp-session\"/></stream:features>"
[error] GenServer #PID<0.1127.0> terminating
** (UndefinedFunctionError) function :crypto.rand_bytes/1 is undefined or private
    (crypto) :crypto.rand_bytes(2)
    (romeo) lib/romeo/stanza.ex:340: Romeo.Stanza.id/0
    (romeo) lib/romeo/stanza.ex:148: Romeo.Stanza.iq/2
    (romeo) lib/romeo/transports/tcp.ex:119: Romeo.Transports.TCP.bind/1
    (romeo) lib/romeo/transports/tcp.ex:66: Romeo.Transports.TCP.start_protocol/1
    (romeo) lib/romeo/connection.ex:90: Romeo.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: %Romeo.Connection{component: false, features: %Romeo.Connection.Features{amp?: false, compression?: false, mechanisms: [], registration?: false, stream_management?: false, tls?: false}, host: "fcm-xmpp.googleapis.com", jid: "xxxx@gcm.googleapis.com", legacy_tls: true, nickname: "", owner: #PID<0.1126.0>, parser: nil, password: "xxxx", port: 5235, preferred_auth_mechanisms: [], require_tls: true, resource: "", rooms: [], socket: nil, socket_opts: [], ssl_opts: [], stream_id: nil, timeout: 5000, transport: Romeo.Transports.TCP}
[info] Application 
```

Is there a problem in romeo?
Thanks

**Comment by romaluca** [comment]
I updated to git version

**Comment by scrogson** [comment]
Ah, this is probably because you're using a more up-to-date erlang/OTP version where `:crypto.rand_bytes` was removed. I probably need to publish a new hex version...but the test suite is currently broken and I haven't had time to fix.
